### PR TITLE
Only enable MT_OCTREE (multi-thread) in Release mode only

### PR DESCRIPTION
**Pull request by dgirardeau**

### CODE REVIEW

**Comment by quepas** [comment]
@dgirardeau This pull request has removed the existence check for `CC_CORE_LIB_USES_QT_CONCURRENT` identifier in `DgmOctree.cpp` file. As a result, the compilation without `QT` is no longer possible (compilation results now in error about missing `QT` headers). Is this the desired result?

**Comment by dgirardeau** [comment]
Ah no 😓

**Comment by quepas** [comment]
@dgirardeau I saw the correction. Thank you! Great project btw :)

**Comment by dgirardeau** [comment]
Yep, hopefully it did the trick ;)

**Comment by quepas** [comment]
It works, I have just checked :)

**Pull request merged**
