### PR TITLE
missing tons of ignore items

### PR DESCRIPTION
**Pull request by WargodHernandez**
I took a look at my local copy change list and had 90ish files that git wanted to add.
Most of this is copy/pasted from CC, just adding the CMake list at the bottom and removed a few CloudCompare specific items

### CODE REVIEW

**Comment by asmaloney** [comment]
Eclipse? Mr Developer? There's way too much random stuff in there.

I'd be more in favour of adding things as we run across them.

I actually don't show anything on my side at all - are you building it in place or are you doing a shadow build?

**Comment by WargodHernandez** [comment]
this is just from visual studio opening the folder... not even building it
image

I assumed the ignore list grew over time on CC as needed (I know I've added to it). So I used that as a starting point and just took out items that were explicitly for the other repo. and added the recommended contents for CMake projects according to GitHubs template

**Comment by asmaloney** [comment]
So what you're showing there should just need `.vs` and `out/build` in gitignore. (Don't understand why it's putting out/build there, but who knows the mysterious ways of MSVC?)

I'd really rather build it up than trying to take a shotgun approach since we are starting fresh with this lib.

I think a lot of what's in CC's was from before we had shadow builds (build_64bits_msvc10?).

**Comment by WargodHernandez** [comment]
Fair enough, I tested out with visual studio and visual studio code and only included the minimum required.

**Pull request merged**
