### PR TITLE
Scalar field improvements

### PR DESCRIPTION
**Pull request by tpwrules**
Please see commits for details.

### CODE REVIEW

**Comment by tpwrules** [comment]
@dgirardeau Hello, would like to make sure this gets reviewed.

**Comment by dgirardeau** [comment]
Ah, I forgot about this PR sorry.

Is it only about syntax?

**Comment by dgirardeau** [comment]
Sorry I fail to see what's optimized / improved 😅

**Comment by tpwrules** [comment]
1. The first commit allows us to change to calculate `m_minValue` and `m_maxValue` in the future by making sure it is only accessed through `getMin()` and `getMax()`
2. The second commit changes the loop to update a local copy of `minValue` and `maxValue` and then assign them to the member variables after the loop. This avoids the need to update the member copies and improves performance by about 30%. I noticed that computing min and max is an operation where a lot of time is spent in my tests so this is a worthwhile improvement.
3. As a side effect of the above, the logic is rearranged so that the member copies are always updated. Previously, the member variables would not be updated properly if there were points in the cloud, but all were the invalid value; the member variables would keep their previous value. Now in this case the min and max are set to 0.

**Comment by dgirardeau** [comment]
On which OS have you performed your benchmarks? Not sure to grasp why updating the members would be slower 🤔

**Comment by dgirardeau** [comment]
And just to be sure again, was it in Release or Debug mode?

**Comment by tpwrules** [comment]
I checked on x86_64 Linux in Release mode. The compiler has to keep reading and writing the member variables in memory each loop iteration so that they have the latest value, I'm assuming in case of an exception. If locals are used then they can be kept in registers. I checked the assembly code.

**Comment by dgirardeau** [comment]
Wow, that's good to know. And I guess it must be the same on Windows if that's the explanation ... I guess there are other places where this happens then.

**Review by dgirardeau — APPROVED** [review]

**Pull request merged**
